site_name: j2f5
site_description: j2f5 ...
site_url: https://github.com/
repo_name: simonkowallik/j2f5
repo_url: https://github.com/simonkowallik/j2f5
theme:
  name: material
  palette:
  - scheme: default
    primary: red
    accent: green
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: red
    accent: green
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
markdown_extensions:
- toc:
    permalink: true
- pymdownx.highlight:
    linenums: true
- markdown.extensions.codehilite:
    guess_lang: true
- pymdownx.details
- pymdownx.superfences
- admonition
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
